---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - patch
  - apiGroups:
      - apps
    resources:
      - deployments/scale
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - argoproj.io
    resources:
      - rollouts
    verbs:
      - get
      - list
      - watch
      - patch
  - apiGroups:
      - argoproj.io
    resources:
      - rollouts/scale
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - ottoscaler.io
    resources:
      - policies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ottoscaler.io
    resources:
      - policies/finalizers
    verbs:
      - update
  - apiGroups:
      - ottoscaler.io
    resources:
      - policies/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - ottoscaler.io
    resources:
      - policyrecommendations
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ottoscaler.io
    resources:
      - policyrecommendations/finalizers
    verbs:
      - update
  - apiGroups:
      - ottoscaler.io
    resources:
      - policyrecommendations/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - your-group.io
    resources:
      - policyrecommendations
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
  - apiGroups:
      - keda.sh
    resources:
      - scaledobjects
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
