apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-event-data-config
  labels:
    app.kubernetes.io/name: configmap
    app.kubernetes.io/instance: ottoscalr-manager
    app.kubernetes.io/created-by: ottoscalr
    app.kubernetes.io/part-of: ottoscalr
    {{- include "ottoscalr.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
{{- if .Values.addCustomEventData }}
  7f8b9c83: '{"eventId":"7f8b9c83","eventName":"Outlier","startTime":"2023-07-27 04:00","endTime":"2023-07-27 05:00"}'
  7f8b9c84: '{"eventId":"7f8b9c84","eventName":"Outlier","startTime":"2023-08-02 21:00","endTime":"2023-08-02 23:59"}'
{{- end }}
