apiVersion: v1
kind: Service
metadata:
  name: ottoscalr-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: ottoscalr
    {{- include "ottoscalr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: ottoscalr
